### ISSUE TITLE
Add YAML REST tests for API spec

### ISSUE THREAD

**Issue by dblock** [dblock/opensearch-api#1]
Tried adding YAML REST tests for the API, getting `java.lang.RuntimeException: Failure at [/20_spec:2]: rest api [api] doesn't exist in the rest spec`.

1. Create `resources/rest-api-spec/test/20_spec.yml`.

```yaml
"Test that the plugin returns an API spec":
  - do:
      api: {}

  - match:
      $body: /^API SPEC\n$/
```

2. Add to resources in `build.gradle`.

```
restResources {
    restApi {
        includeCore '_common', 'cat', 'api'
    }
}
```

3. `./gradlew yamlRestTest` will fail.
